services:
  database:
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
     - POSTGRES_PASSWORD=pass123
     - POSTGRES_DB=infoDB
    
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports: 
     - 8080:8080